# proto-file: https://github.com/intrinsic-ai/sdk/blob/main/intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "com.example"
    name: "point_storage_service"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "Stores coordinates of 3d points in the key-value storage."
  }
  display_name: "Point storage"
}
service_def {
  service_proto_prefixes: "/point_storage.PointStorageService/"
  real_spec {
    image {
      archive_filename: "point_storage_service_image.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "point_storage_service_image.tar"
    }
  }
}
