# proto-file: https://github.com/intrinsic-ai/sdk/blob/main/intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "ai.intrinsic"
    name: "platform_http_server"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "A web server for static content."
  }
  display_name: "Platform HTTP Server"
}
service_def {
  http_config: {}
  supports_service_state: true
  real_spec {
    image {
      archive_filename: "platform_http_server_image.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "platform_http_server_image.tar"
    }
  }
}
