name: 'Deploy Intrinsic Assets'
description: 'Installs and adds skills and services to a solution.'

inputs:
  organization:
    description: 'The Intrinsic organization'
    required: true
  solution-id:
    description: 'The Intrinsic solution ID'
    required: true
  asset-prefix:
    description: 'The namespace prefix for assets (e.g., com.example, ai.intrinsic)'
    required: false
    default: 'ai.intrinsic'
  skills:
    description: 'Comma-separated list of skill targets'
    required: false
  services:
    description: 'Comma-separated list of service targets'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Skills
      shell: bash
      run: |
        if [ -z "${{ inputs.skills }}" ]; then
          echo "No skills to install."
          exit 0
        fi
        
        echo "Fetching list of currently installed sideloaded skills..."
        INSTALLED_SKILLS=$(inctl skill list --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}" --filter "sideloaded" 2>&1)
        
        IFS=',' read -ra SKILL_ARRAY <<< "${{ inputs.skills }}"
        for SKILL in "${SKILL_ARRAY[@]}"; do
          SKILL=$(echo "$SKILL" | xargs) # trim whitespace
          if [ -z "$SKILL" ]; then continue; fi
          
          echo "Processing skill: $SKILL"
          skill_package="${SKILL%:*}"
          skill_package_dir="${skill_package#//}" # Remove leading //
          skill_name=$(basename "$skill_package_dir")
          skill_target="${SKILL##*:}"

          FULL_SKILL_NAME="${{ inputs.asset-prefix }}.${skill_name}"
          
          if echo "$INSTALLED_SKILLS" | grep -q "$FULL_SKILL_NAME"; then
            echo "Skill '$FULL_SKILL_NAME' is already installed. Removing..."
            inctl asset uninstall "$FULL_SKILL_NAME" --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}"
          fi
          
          BUNDLE_PATH="bazel-bin/${skill_package_dir}/${skill_target}.bundle.tar"
          echo "Installing skill from $BUNDLE_PATH"
          inctl skill install "$BUNDLE_PATH" --solution "${{ inputs.solution-id }}" --org "${{ inputs.organization }}"
        done

    - name: Install and Add Services
      shell: bash
      run: |
        if [ -z "${{ inputs.services }}" ]; then
          echo "No services to install/add."
          exit 0
        fi

        echo "Fetching list of currently installed services..."
        INSTALLED_SERVICES_LIST=$(inctl asset list --asset_types="service" --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}")
        
        declare -a SERVICES_TARGET_NAMES
        
        echo "--- Installing Services ---"
        IFS=',' read -ra SERVICE_ARRAY <<< "${{ inputs.services }}"
        for SERVICE in "${SERVICE_ARRAY[@]}"; do
          SERVICE=$(echo "$SERVICE" | xargs) # trim whitespace
          if [ -z "$SERVICE" ]; then continue; fi

          echo "Processing service: $SERVICE"
          service_package="${SERVICE%:*}"
          service_package_dir="${service_package#//}" # Strip //
          service_target="${SERVICE##*:}"
          
          SERVICES_TARGET_NAMES+=("$service_target")
          FULL_SERVICE_NAME="${{ inputs.asset-prefix }}.${service_target}"
          
          if echo "$INSTALLED_SERVICES_LIST" | grep -q "$FULL_SERVICE_NAME"; then
            echo "Service '$FULL_SERVICE_NAME'is already installed. Deleting and uninstalling..."
            inctl service delete "${service_target}" --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}"
            inctl asset uninstall "$FULL_SERVICE_NAME" --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}"
            echo "Waiting for 20 seconds..."
            sleep 20
          fi
          
          BUNDLE_PATH="bazel-bin/${service_package_dir}/${service_target}.bundle.tar"
          echo "Installing service from $BUNDLE_PATH"
          inctl service install "$BUNDLE_PATH" --solution "${{ inputs.solution-id }}" --org "${{ inputs.organization }}"
        done
        
        echo "--- Adding Services ---"
        if [ ${#SERVICES_TARGET_NAMES[@]} -eq 0 ]; then
          echo "No services were installed, skipping 'add' step."
          exit 0
        fi
        
        echo "Fetching full list of available assets to find service full names..."
        LATEST_ASSET_LIST=$(inctl asset list --org "${{ inputs.organization }}" --solution "${{ inputs.solution-id }}")
        
        for SERVICE_SHORT_NAME in "${SERVICES_TARGET_NAMES[@]}"; do
          SERVICE_FULL_NAME=""
          while IFS= read -r full_service_name; do
            if [[ "$full_service_name" == *".$SERVICE_SHORT_NAME" ]]; then
               SERVICE_FULL_NAME=$(echo "$full_service_name" | xargs)
               break
            fi
          done <<< "$LATEST_ASSET_LIST"

          if [ -n "$SERVICE_FULL_NAME" ]; then
            echo "Adding service '$SERVICE_FULL_NAME' as '$SERVICE_SHORT_NAME'..."
            inctl service add "$SERVICE_FULL_NAME" \
              --org "${{ inputs.organization }}" \
              --solution "${{ inputs.solution-id }}" \
              --name "$SERVICE_SHORT_NAME"
          else
            echo "::warning::Could not find full name for short name '$SERVICE_SHORT_NAME'. Skipping 'add'."
          fi
        done
