name: Build and Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be  #v1.3.1
        with:
          tool-cache: verbose_failures
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8  #v0.15.0
        with:
         # Avoid downloading Bazel every time.
         bazelisk-cache: true
         # Store build cache per workflow.
         disk-cache: ${{ github.workflow }} 
         # Cache external/ repositories
         external-cache: true
         # Share repository cache between workflows.
         repository-cache: true

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - name: Update SDK to latest
        run: bazel fetch --repo=@ai_intrinsic_sdks --force

      - name: Build And Test
        run: bazel test --verbose_failures --test_output=errors --nobuild_tests_only //...
